### ISSUE TITLE
Help search engines find and return the latest docs for the latest package

### ISSUE THREAD

**Issue by sethladd** [astashov/dartdocs.org#1]
Reason: we'll have lots of versions of docs for a package, and we probably want search engines to give users the _latest_ copy of the docs. We don't want an old version to appear at the top of the search results.

**Comment by sethladd** [comment]
By setting a rel="canonical" we can tell search engines what the canonical doc is for a package. For example, that's probably: `https://www.dartdocs.org/documentation/jquery_for_pub/latest/index.html`  (note the use of latest here)

We could try dartdoc's support for --rel-canonical-prefix.

For example, when generating docs for the _foo_ package, we could do:

`dartdoc --rel-canonical-prefix=https://www.dartdocs.org/documentation/foo/latest .`

(assuming that dartdocs.org supports a "latest" path which redirects appropriately)

**Comment by astashov** [comment]
So, we need some sort of proxy, which will do 302 redirect from `https://www.dartdocs.org/documentation/jquery_for_pub/latest/**/*` to `https://www.dartdocs.org/documentation/jquery_for_pub/1.2.3/**/*`, right?

**Comment by kevmoo** [comment]
I'd add one more:

`https://www.dartdocs.org/documentation/jquery_for_pub/**/*` to `https://www.dartdocs.org/documentation/jquery_for_pub/1.2.3/**/*`

**Comment by kevmoo** [comment]
_or_ `https://www.dartdocs.org/documentation/jquery_for_pub/` can list all of the generated docs, that'd be nice, too

**Comment by astashov** [comment]
Okay, it will require adding some dynamic component to our static site (i.e. some proxy, which will redirect to the latest package). Or we can just copy latest package to `https://www.dartdocs.org/documentation/jquery_for_pub` every time we generate the latest version package docs. Its simpler, though adds some redundancy (not a big deal, IMHO, though).

But anyway, for that we need pub.dartlang.org to return publish dates for the package versions. How hard would it be to add that to API? @sethladd ?

**Comment by sethladd** [comment]
Not sure it requires a dynamic component. Just rewrite `https://www.dartdocs.org/documentation/jquery_for_pub/latest` whenever you generate a new set of docs. That `/latest` should have a meta redirect in the `<head>`.

(I think this is exactly what we do in the current dartdocs)

**Comment by astashov** [comment]
Oh, that is enough for Google search bots? Then that's cool, I can definitely do that.

Is there any way to add `published_at` to pub.dartlang.org, anyway? How hard it is? I can infer the latest version from the version numbers, but that's not 100% reliable, if the author of the package doesn't follow semver, or just some meaningful ver :)

**Comment by sethladd** [comment]
Curious, why do you need to know the `published_at` ? Should "package/latest" just point to the latest version, as sorted by semvers ?

**Comment by astashov** [comment]
Yeah, but again - sometimes it's hard to figure out what's the latest version. Like `0.0.1-alpha.1` and `0.0.1-alpha.11` is already pretty tricky to figure out, or something like `0.9.0-dev+1` and `0.9.0+1` - which one is the latest? We don't enforce semver on `pub publish`, so package authors could be pretty creative, making it harder to sort correctly.

**Comment by kevmoo** [comment]
Nice! Awesome work, @astashov

**Comment by astashov** [comment]
Thanks :)
