### ISSUE TITLE
Integration with Dash

### ISSUE THREAD

**Issue by astashov** [astashov/dartdocs.org#12]
Hey @Kapeli, the new version of dartdocs.org is up and running.
It has https://www.dartdocs.org/index.json, which contains all the versions of all the packages, and links to the index.html for each package, and to package.tar.gz, which contains whole package docs archived.

Is that enough for you to integrate with Dash? Or you need something else?

Thanks!

**Comment by Kapeli** [comment]
Looks great! I don't think I'll need anything else. I should be able to add support for Dart packages in the next version of Dash.

Caching the index.json should be fun :+1:. Thanks a lot for your help!

**Comment by sethladd** [comment]
@Kapeli nice!

**Comment by Kapeli** [comment]
Found one issue: the versions for each package are listed inside a dictionary/object. JSON defines object keys as unsorted and the Cocoa implementation of JSON serialisation relies on that.

What happens: once I parse the JSON the order of the versions is lost and they get randomly sorted. This makes it hard to know which one is the latest version of a package.

Could this be changed so that the versions a package has are stored in an array instead?

Something like this:

``` json
"ChronosGL": [  
    {  
        "1.0.0" : {  
            "html" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.0/index.html",
            "archive" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.0/package.tar.gz"
        }
    },
    {  
        "1.0.1" : {  
            "html" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.1/index.html",
            "archive" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.1/package.tar.gz"
        }
    }
]
```

**Comment by astashov** [comment]
Whoops, good point. Will fix.

**Comment by astashov** [comment]
Hmm, but if you know the exact name/version, would be nice to be able to reach it without iterating through all the versions.

What about something like this:

`````` json
```json
"ChronosGL": {
    "versions_order": ["1.0.0", "1.0.1"],
    "versions": {
        "1.0.0" : {  
            "html" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.0/index.html",
            "archive" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.0/package.tar.gz"
        },
        "1.0.1" : {  
            "html" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.1/index.html",
            "archive" : "https://www.dartdocs.org/documentation/ChronosGL/1.0.1/package.tar.gz"
        }
    }
}
``````

**Comment by Kapeli** [comment]
That's fine for me :+1:

**Comment by astashov** [comment]
Awesome, I'll try to implement this tonight.

**Comment by astashov** [comment]
Actually, done - https://www.dartdocs.org/index.json
Looks good?

**Comment by Kapeli** [comment]
Perfect. Thanks a lot for adding this so fast!

**Comment by Kapeli** [comment]
All done. I've released a beta here: https://rink.hockeyapp.net/api/2/apps/173bd84c757f0d5099722824a23aa7d5/app_versions/22?format=zip.

If all goes well this should go live in 1 week or so, depending on App Store review times.

**Comment by astashov** [comment]
Works for me! Thanks a lot!
