### ISSUE TITLE
Update to latest Dart sdk - 1.13.0-dev.7.10

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#13]
We'd LOVE to make sure everything is looking good before we release

**Comment by sethladd** [comment]
Are you asking that we rebuild the whole site with the latest dev channel? Shouldn't we wait for the stable version?

**Comment by astashov** [comment]
If you want to rebuild the whole site: https://github.com/astashov/dartdocorg#common-tasks - there are instructions how to do that.

If you just want to update the Dart SDK version, without regenerating everything, then you just need to stop and start the instances:

``` bash
$ gcloud compute instance-groups managed resize dartdocs-package-generators --size 0 --zone us-central1-f
$ sleep 60
$ gcloud compute instance-groups managed resize dartdocs-package-generators --size 1 --zone us-central1-f
$ gcloud compute instance-groups managed resize dartdocs-index-generators --size 0 --zone us-central1-f
$ sleep 60
$ gcloud compute instance-groups managed resize dartdocs-index-generators --size 1 --zone us-central1-f
```

**Comment by astashov** [comment]
Can be closed?

**Comment by kevmoo** [comment]
WFM - I checked that one to make sure there was little confusion
