### ISSUE TITLE
Provide a way to manually regenerate package docs for one package

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#15]
It'd be great to be able to validate that an update works or fixes an issue, etc

**Comment by astashov** [comment]
It's in README :)

> Regenerate just one specific package
> Just simply run:
> 
> $ dart bin/package_generator.dart --name blah --version 1.2.3
> And it will regenerate the package and override it on the https://www.dartdocs.org.

**Comment by kevmoo** [comment]
Thanks!
