### ISSUE TITLE
Get retry logic from dart-lang/coverage

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#17]
https://github.com/dart-lang/coverage/blob/master/lib/src/util.dart#L12

It's a nice implementation – copy the tests, too.

**Comment by astashov** [comment]
How's it better than the current one?

**Comment by kevmoo** [comment]
It's not recursive – and it's tested.

**Comment by astashov** [comment]
Well, mine is tested as well - on thousands of packages. :) I also used a similar one in Mixbook.
The coverage's one seems like doesn't support increasing delays (like, 5, 15, 30 seconds after every failure) and number of possible failures, after which it should give up. Also I don't think it should be retries' responsibility to handle timeouts, `retry` should just, well, retry, and it's up to the retried block to fire a timeout exception if applicable.

**Comment by kevmoo** [comment]
Not a huge deal at all. Just a refactor thought.

It all seems to be working amazingly well. :smile:

**Comment by astashov** [comment]
Okay, WNF then :)
