### ISSUE TITLE
Regenerate docs for built_collection

### ISSUE THREAD

**Issue by kwalrath** [astashov/dartdocs.org#19]
It looks like dartdocs.org might be generating library docs now (after the fix for https://github.com/dart-lang/dartdoc/issues/1005), but the docs for https://www.dartdocs.org/documentation/built_collection/1.0.0/built_collection/built_collection-library.html still show "Library not documented" despite the doc comments existing (see https://github.com/google/built_collection.dart/blob/master/lib/built_collection.dart).

Is that because built_collection 1.0.0 was uploaded too long ago? (August, according to https://pub.dartlang.org/packages/built_collection)

If so, could you rerun the docs on built_collection (and any other packages that have "Library not documented)"?

**Comment by astashov** [comment]
Okay, I tried with dartdoc 0.8.0 - it was regenerated succesfully - https://www.dartdocs.org/documentation/built_collection/1.0.0/built_collection/built_collection-library.html.
How many packages do we expect affected? Should we just regenerate everything with the latest dartdoc?

**Comment by kwalrath** [comment]
That was quick! Thank you!

Personally, I'd regenerate everything, but I don't know if there's any risk associated with doing so.

**Comment by astashov** [comment]
Ah, wait, but latest dev build still has 0.7.4. If I try to regenerate it with 0.7.4, it will have "Library not documented". And we use dartdoc from the latest SDK on the dartdocs servers. Let's regenerate everything once latest SDK has dartdoc version 0.8.0, okay?

**Comment by kwalrath** [comment]
Makes sense.

**Comment by keertip** [comment]
The next dev build of the sdk will have dartdoc 0.8.0

**Comment by astashov** [comment]
Nice, let me know once it's available as a deb package, and I'll regenerate everything.

**Comment by kevmoo** [comment]
@astashov We're out with `1.13.0-dev.7.12` which has dartdoc 0.8 – we should do a full build.

**Comment by astashov** [comment]
Okay, I'll regenerate

**Comment by astashov** [comment]
Done
