### ISSUE TITLE
Try out latest dev channel - 1.14.0-dev.4.0

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#24]
I think [this](https://github.com/astashov/dartdocs.org/issues/22) is fixed – and the output is better in many ways

**Comment by astashov** [comment]
So, switch back to the dev channel?

**Comment by kevmoo** [comment]
Please – we'll keep an eye on the output, but I think it'll end up being much better.

**Comment by astashov** [comment]
Ok done

**Comment by kevmoo** [comment]
Thanks!
