### ISSUE TITLE
upgrade sdk to 1.14.-dev.7.1

### ISSUE THREAD

**Issue by keertip** [astashov/dartdocs.org#25]
The docs for the analyzer package are not being generated. dartdoc was fixed and there is available in 1.14.-dev.7.1. Can you regenerate the docs using this sdk?

**Comment by astashov** [comment]
Just for the analyzer package?

**Comment by keertip** [comment]
Not sure of your setup, but that will work.

**Comment by astashov** [comment]
Ok, done
