### ISSUE TITLE
customize dartdoc package includes for angular2?

### ISSUE THREAD

**Issue by naomiblack** [astashov/dartdocs.org#26]
Hi -- I'm on the Angular team -- we have a very angular-specific problem in that when you run the generic dartdoc command for angular2, you get output from all of our private libs as well as the public ones. So the output on dartdoc.org is misleading, and kind of messy. I'm working on cleaning that up.

Is there any way to modify the command for the angular2 package so that the dartdoc output is restricted to the public libs?

The command I use to do this locally is

```
pub global run dartdoc --include angular2.common,angular2.animate,angular2.instrumentation,angular2.platform.browser,angular2.router,angular2.router.testing,angular2.testing
```

**Comment by astashov** [comment]
I can add these `--include` settings specifically for angular2 in the code.

**Comment by astashov** [comment]
Is that a temporary solution and you will eventually make it work without specific `--include` attr, or it will be forever like that, or `--include` param will change from time to time?

**Comment by sethladd** [comment]
Does the `<nodoc>` work for this use case?

**Comment by naomiblack** [comment]
Sorry I was slow to reply on this. I don't think nodoc works because there are too many libraries to exclude -- we don't want to just drop individual classes, we want entire libs to remain private.

@astashov we will always want to include specific `--include` attrs. The only change I'd envision is that we will probably add some libraries in future so the list of attrs might change. It would be nice for me to be able to provide a list somewhere in a settings file that you automatically pick up.

**Comment by astashov** [comment]
What if dartdoc used some `.dartdoc` file, which would contain the list of default params, and when you run `dartdoc` on that repo, it'd add the settings from that file? Like:

``` bash
$ cat .dartdoc
--include angular2.common,angular2.animate,angular2.instrumentation,angular2.platform.browser,angular2.router,angular2.router.testing,angular2.testing
$ pub global run dartdoc
# Will run dartdoc --include ...
```

Similar to what e.g. RSpec is doing. @sethladd what do you think?

**Comment by naomiblack** [comment]
That would work for me, but means changing dartdoc. As a short-term measure, could we also fix what is on dartdocs.org now?

**Comment by astashov** [comment]
Okay, I'll hardcode that exception into dartdocs.org for now. But I'd really want to switch to better long-term solution asap. @sethladd do you think you can add that config file to dartdocs?

**Comment by naomiblack** [comment]
I've sent email to seth, keerti, and a bunch of folks who work on dartdocs internally to see if we could add that as a feature. thanks1

**Comment by sethladd** [comment]
Yup, let's talk to @keertip to see what we can do. Thanks!

**Comment by keertip** [comment]
@naomiblack , the `<nodoc>` tag should work for libraries too. Would adding the tag to library directives solve the problem?

**Comment by naomiblack** [comment]
@keertip could you help me to do this for Angular? It might be my lack of knowledge but that seems like a huge job... this approach would be much simpler for us.

**Comment by keertip** [comment]
yes, can help.

**Comment by keertip** [comment]
spoke to @naomiblack , and here's what we decided. 

Not going with the `<nodoc>` tag, as it would take some amount of work to get it into angular. Will look at modifying dartdoc to look for a particular file to read options from.

@astashov , in the meantime could you add the `--include` and the list of libraries, so that the angular docs are cleanly generated?

**Comment by astashov** [comment]
Okay, will try to do by the weekend

**Comment by astashov** [comment]
Okay, from now on, all the new versions of `angular2` will be generated with that list of libraries.
@naomiblack, @keertip please let me know once you add the support of options file, so I could remove that hardcoded `angular2` condition.

Thanks!

**Comment by astashov** [comment]
https://www.dartdocs.org/documentation/angular2/2.0.0-beta.11/index.html
