### ISSUE TITLE
Document complete workflow for complete docs rebuild

### ISSUE THREAD

**Issue by sethladd** [astashov/dartdocs.org#3]
Should be:

```
$ gcloud compute instance-groups managed resize dartdocs-package-generators --size 0 --zone us-central1-f
$ dart bin/bump_docs_version.dart
$ gcloud compute instance-groups managed resize dartdocs-package-generators --size 11 --zone us-central1-f
… after its done …
$ dart bin/purge_cdn_cache.dart
```

So, the command "gcloud compute instance-groups managed resize dartdocs-package-generators --size 11 --zone us-central1-f” sets the number of instances in dartdocs-package-generators group according to the ‘—size’ argument.
By default, you only can launch 24 CPU units per google cloud project, so, by default we are limited with 11 instances.

It takes ~20-24 hours to regenerate the whole pub with 11 instances.

It doesn’t scale down automatically, you have to use the command "gcloud compute instance-groups managed resize dartdocs-package-generators --size 1 --zone us-central1-f” to scale it back to one instance once they are done with regenerating everything.

Maybe we should add this to the README? (it's hinted there, but not this exact order)

**Comment by astashov** [comment]
Yeah, I'm still working on README, will add the common use cases (regenerate everything, regenerate just one package, scale up-down, etc) to it.

**Comment by astashov** [comment]
Fixed
