### ISSUE TITLE
Instead of generating angular2 API docs, link to them

### ISSUE THREAD

**Issue by kwalrath** [astashov/dartdocs.org#30]
As we discussed in https://github.com/dart-lang/angular2/pull/42, https://www.dartdocs.org/documentation/angular2/latest/index.html needs to point to the docs at https://angular.io/docs/dart/latest/api/. Here’s what that page might say.
# Title

angular2 - Dart API docs
# Headings

(It’d be fine to have the same blue header as the current docs, but without the “LIBRARIES” link. So that’d be:)

angular2

PACKAGE
**angular2**
# Body

The Dart API docs for angular2 are on angular.io:

**Comment by kwalrath** [comment]
@astashov making sure you see this...

**Comment by astashov** [comment]
Oh right, I forgot, I'm so sorry :( Bummer :( Will try to get to that soon.

**Comment by kwalrath** [comment]
No worries, I should've followed up before!

**Comment by astashov** [comment]
Done, gonna look like this: https://www.dartdocs.org/documentation/angular2/2.0.0-beta.20/index.html

**Comment by kwalrath** [comment]
Thanks!!
