### ISSUE TITLE
Upgrade and use sdk 1.19.1 stable

### ISSUE THREAD

**Issue by keertip** [astashov/dartdocs.org#32]
The docs for [code_builder](https://www.dartdocs.org/documentation/code_builder/0.1.3/log.txt) are broken since the package requires sdk 1.19.1 and above.

[See here](https://github.com/dart-lang/code_builder/blob/master/pubspec.yaml)

**Comment by keertip** [comment]
dartdoc in 1.19.1 and above fails while linking in crossdart, this [issue](https://github.com/dart-lang/dartdoc/issues/1254) has to be fixed and new version of dartdoc rolled into the sdk before dartdocs.org can do the upgrade.

**Comment by filiph** [comment]
Even better, upgrade to 1.20 now that it's available in stable.

cc @astashov — let us know if you are able to do this in time for Dart Dev Summit (next Tuesday).

**Comment by astashov** [comment]
Upgraded to 1.20.1

**Comment by matanlurey** [comment]
Ping - this still doesn't seem to work.

https://www.dartdocs.org/documentation/code_builder/0.1.3/

**Comment by astashov** [comment]
I regenerated code_builder docs, should work now.

**Comment by matanlurey** [comment]
Thank you!
