### ISSUE TITLE
Can we upgrade and rebuild to get the latest dartdoc + SDK?

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#36]
Especially to pull in support for generic methods

CC @nex3

**Comment by astashov** [comment]
Done

```
$ dart --version
Dart VM version: 1.21.0 (Wed Dec  7 14:47:52 2016) on "linux_x64"
```

**Comment by kevmoo** [comment]
Sweet! Did you schedule a rebuild, too?

**Comment by astashov** [comment]
Rebuild of all the packages?

**Comment by kevmoo** [comment]
@astashov Curious what you usually do – do you do a full rebuild or just wait for packages to be published?

**Comment by astashov** [comment]
Usually I just wait for new versions, I don't usually do a full rebuild.

**Comment by kevmoo** [comment]
Cool – just checkin'

**Comment by nex3** [comment]
I hear that the latest Dartdoc update adds support for generic methods, which is a pretty major improvement to documentation. I think it might be major enough to warrant rebuilding the docs for at least the latest versions of all the packages.
