### ISSUE TITLE
Update text/URL for angular2 API docs

### ISSUE THREAD

**Issue by kwalrath** [astashov/dartdocs.org#37]
They've moved from https://angular.io/docs/dart/latest/api to https://webdev.dartlang.org/angular/api, so the text should be something like this:

The Dart API docs for angular2 are on webdev.dartlang.org:
https://webdev.dartlang.org/angular/api

(Fortunately, the redirect works.)

**Comment by kwalrath** [comment]
It looks like the relevant file is [/resources/angular2.html](https://github.com/astashov/dartdocs.org/blob/a1d88abd9fc3e54095d6fff7646f41913766884d/resources/angular2.html).

Would you like me to create a PR, @astashov?

**Comment by astashov** [comment]
Sure, that'd be cool! Thanks!
