### ISSUE TITLE
Broken link to Dart docs (404)

### ISSUE THREAD

**Issue by nex3** [astashov/dartdocs.org#38]
_From @fsc8000 on December 22, 2016 11:25_

https://www.dartdocs.org/documentation/test/0.12.18/

which is linked from its pub page (https://pub.dartlang.org/packages/test)

gives a 404 error.

Same for the link to the sources (https://www.crossdart.info/p/test/0.12.18/)

_Copied from original issue: dart-lang/test#516_

**Comment by nex3** [comment]
_From @matanlurey on December 22, 2016 18:58_

Looks like it "caught up" FWIW.

**Comment by nex3** [comment]
_From @matanlurey on December 22, 2016 18:59_

Rather dartdoc did, crossdart is still behind/404ing

**Comment by astashov** [comment]
Fixed
