### ISSUE TITLE
versions of the package are not sorted with latest first

### ISSUE THREAD

**Issue by keertip** [astashov/dartdocs.org#4]
Take a look at the`analyzer` package - very hard to figure out which is the latest, that's the one I want to see the documentation for.

![screenshot from 2015-10-22 09 45 35](https://cloud.githubusercontent.com/assets/2192312/10671877/d91e2dfc-78a1-11e5-96db-7e24519220c4.png)

**Comment by srawlins** [comment]
Looks like alphabetical sorting, rather than numerical-between-the-dots.

**Comment by kevmoo** [comment]
Actually, you should use the `pub_semver` package to sort these items. It provides the correct sort logic

**Comment by astashov** [comment]
Ah, thanks for the advice, @kevmoo. Will do!
