### ISSUE TITLE
Upgrade to dartdoc 0.9.12

### ISSUE THREAD

**Issue by keertip** [astashov/dartdocs.org#41]
Anton, not sure if you use dartdoc from the SDK or from pub. There is a new version 0.9.12 with fix for https://github.com/dart-lang/dartdoc/issues/1328. 

It is on pub and will be in the next dev sdk, the second one for 1.23. dartdocs.org should be updated to use this.

**Comment by astashov** [comment]
We currently use it from `pub`. I'll update it.

**Comment by astashov** [comment]
Done
