### ISSUE TITLE
Upgrade SDK to 1.23.0-dev.5.0

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#42]
See https://github.com/dart-lang/http/issues/66

We have a package that requires the latest dev build.

This shouldn't affect other packages, but would unblock pkg/http

**Comment by mit-mit** [comment]
Hi @astashov any chance we can roll the SDK?

**Comment by astashov** [comment]
I thought we use stable versions of SDK for dartdocs.org. Should we switch back to dev builds again?

**Comment by kevmoo** [comment]
In this case, yes – but it's a special case.

In general, sticking w/ stable is goodness.

Thanks!

**Comment by astashov** [comment]
Done!
