### ISSUE TITLE
path documentation is down

### ISSUE THREAD

**Issue by nex3** [astashov/dartdocs.org#49]
_From @kirbyfan64 on June 11, 2017 23:47_

http://www.dartdocs.org/documentation/, which is linked from the pub package, is currently a 404.

_Copied from original issue: dart-lang/path#27_

**Comment by nex3** [comment]
Note that there doesn't seem to be a build failure for `path` listed [on the failures page](https://www.dartdocs.org/failed/index.html).

**Comment by astashov** [comment]
Damn, the generator script stopped generating and monit didn't notify me, weird.

**Comment by alan-knight** [comment]
I think this is probably the same problem as dart-lang/core#515 , the site is using a broken version of dartdoc.

**Comment by astashov** [comment]
Should be fixed now.

**Comment by kwalrath** [comment]
Confirmed that https://www.dartdocs.org/documentation/path/latest works (redirects to https://www.dartdocs.org/documentation/path/1.4.2/index.html).
